#@TYPE: Machine
#@NAME: IMDT Pico Board
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for the IMDT Pico Board
#@MAINTAINER: Lewis Purvis <lewisp@imd-tec.com>

UBOOT_CONFIG_BASENAME = "imx8mp_imdt_pico"

require conf/machine/include/imx8mp-imdt-pico.inc
