#@TYPE: Machine
#@NAME: IMDT Pico e Board [IM-PCA-0010]
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for the IMDT Pico-E Board
#@MAINTAINER: William Bagshaw <william.bagshaw@imd-tec.com>

UBOOT_CONFIG_BASENAME = "imx8mp_imdt_pico_e"

require conf/machine/include/imx8mp-imdt-pico.inc

MACHINEOVERRIDES .= ":imdt-pico-e"

MACHINE_FEATURES:append = "imdt-can"