#@TYPE: Machine
#@NAME: IMDT Pico em Board [IM-PCA-0019] [IM-PCA-0022] [IM-PCA-0023]
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for the IMDT Pico-EM Board
#@MAINTAINER: Lewis Purvis <lewisp@imd-tec.com>

UBOOT_CONFIG_BASENAME = "imx8mp_imdt_pico_em"

require conf/machine/include/imx8mp-imdt-pico.inc

MACHINEOVERRIDES .= ":imdt-pico-em"
