#@TYPE: Machine
#@NAME: IMDT Pico Board
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for the IMDT Pico Board with ARMv8a tuning.
#@MAINTAINER: Lewis Purvis <lewisp@imd-tec.com>

UBOOT_CONFIG_BASENAME = "imx8mp_imdt_pico"
KERNEL_DEVICETREE_BASENAME = "imx8mp-imdt-pico"

require conf/machine/include/imx8mp-imdt-pico-armv8a-tune.inc
require conf/machine/include/imx8mp-imdt-pico.inc
